pipeline{
	agent any
	environment {
		ANYPOINT = credentials('ANYPOINT')
	}
	stages{
		stage('Build'){
			steps{
				withMaven(maven:'maven'){
					bat 'mvn -f employee-service/pom.xml clean install'
				}
			
			}
		
		}
		
		stage('Deploy'){
			steps{
				withMaven(maven:'maven'){
					bat 'mvn -f employee-service/pom.xml package deploy -Danypoint.username=%ANYPOINT_USR% -Danypoint.password=%ANYPOINT_PWD% -Denvironment=Sandbox -DmuleDeploy'
				}
			
			}
		
		}
	
	
	}
	
}